name: diet_mouse_cdiff
channels:
    - bioconda
    - conda-forge
    - R
dependencies:
    - qiime2R
    - r-base
    - r-tidyverse
    - r-ape
    - r-broom
    - r-cowplot
    - r-ggh4x
    - r-ggplot2
    - r-ggpubr
    - r-rstatix
    - r-vegan
    - r-viridis
    - r-magrittr
    - snakemake